### ISSUE TITLE
Oxygen Deployment Issues

### ISSUE THREAD

**Issue by Patrickrgt** [Shopify/gated-hydrogen-example#13]
I'm trying to build and publish to Oxygen, but I'm getting an error saying "Raw mode is not supported on the current process.stdin" tried updating the cli packages but just get other package issues.

To replicate--clone the gated-hydrogen-example repository and Build and Publish to Shopify

Tagging @QuintonC as requested on X

```
Run npx shopify hydrogen deploy

  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
The above error occurred in the <SelectPrompt> component:

       Read about how to prevent this error on
    at SelectPrompt (file:///home/runner/work/my-project-folder/node_modules/@shopify/cli-kit/dist/private/node/ui/components/SelectPrompt.js:12:25)
    at App (file:///home/runner/work/my-project-folder/node_modules/ink/build/components/App.js:18:9)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalApp.
       https://github.com/vadimdemedes/ink/#israwmodesupported

 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 - value (node_modules/ink/build/components/App.js:4[6](https://github.com/Patrickrgt/my-project-folder/actions/runs/10840989004/job/30084290054#step:6:7):31)
 -  (node_modules/ink/build/hooks/use-input.js:34:9)
 -commitHookEffectLis (node_modules/react-reconciler/cjs/react-reconciler.devel
  Mount              opment.js:14[7](https://github.com/Patrickrgt/my-project-folder/actions/runs/10840989004/job/30084290054#step:6:8)78:26)
 -commitPassiveMountO (node_modules/react-reconciler/cjs/react-reconciler.devel
  Fiber              opment.js:16609:11)
 -commitPassiveMountEffect (node_modules/react-reconciler/cjs/react-reconciler.
  _complete               development.js:16569:9)
 -commitPassiveMountEffe (node_modules/react-reconciler/cjs/react-reconciler.de
  ts_begin              velopment.js:16556:7)
 -commitPassiveMountE (node_modules/react-reconciler/cjs/react-reconciler.devel
  fects              opment.js:16544:3)
 -flushPassiveEffect (node_modules/react-reconciler/cjs/react-reconciler.develo
  Impl              pment.js:191[8](https://github.com/Patrickrgt/my-project-folder/actions/runs/10840989004/job/30084290054#step:6:9)2:3)
 -flushPassiveEff (node_modules/react-reconciler/cjs/react-reconciler.developme
  cts            nt.js:1[9](https://github.com/Patrickrgt/my-project-folder/actions/runs/10840989004/job/30084290054#step:6:10)127:14)
 -performSyncWorkOn (node_modules/react-reconciler/cjs/react-reconciler.develop
  oot              ment.js:18184:3)
```
![Image](https://github.com/user-attachments/assets/7a20688b-bfa0-40e3-8cd8-326432db7aa3)

**Comment by QuintonC** [comment]
Hey @Patrickrgt 

Thanks for opening this issue.

It looks like this issue is likely related to some outdated package versions of Hydrogen and other related dependencies. It looks like the error is related to a specific component that's not related to the blockchain feature set, but something more so related to either Hydrogen or Oxygen.

This might be a bit to ask, but could you try updating some dependencies and seeing where that takes you?

**Comment by Patrickrgt** [comment]
> Hey [@Patrickrgt](https://github.com/Patrickrgt)
> 
> Thanks for opening this issue.
> 
> It looks like this issue is likely related to some outdated package versions of Hydrogen and other related dependencies. It looks like the error is related to a specific component that's not related to the blockchain feature set, but something more so related to either Hydrogen or Oxygen.
> 
> This might be a bit to ask, but could you try updating some dependencies and seeing where that takes you?

After updating Hydrogen CLI, Shopify CLI and Remix I came across this error attached below, unsure how to fix it:

"@remix-run/react": "^1.15.0",
"@shopify/cli": "^3.45.0",
"@shopify/cli-hydrogen": "^4.2.1",
"@shopify/remix-oxygen": "^1.1.8",
"@remix-run/dev": "^1.15.0",

I was wondering if you have older Oxygen workflow files with the template because I believe it should be able to deploy with older Oxygen workflow files.

```
Run npm ci
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated @json-rpc-tools/provider@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @json-rpc-tools/utils@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @json-rpc-tools/types@1.7.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
added 2177 packages, and audited 2178 packages in 34s
496 packages are looking for funding
  run `npm fund` for details
72 vulnerabilities (16 low, 17 moderate, 31 high, 8 critical)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
```

```
Run npx shopify hydrogen deploy
  
The above error occurred in the <SelectPrompt> component:
    at SelectPrompt (file:///home/runner/work/aiko-hydrogen/aiko-hydrogen/node_modules/@shopify/cli-kit/dist/private/node/ui/components/SelectPrompt.js:12:25)
    at App (file:///home/runner/work/aiko-hydrogen/aiko-hydrogen/node_modules/ink/build/components/App.js:18:9)
React will try to recreate this component tree from scratch using the error boundary you provided, InternalApp.
  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 - value (node_modules/ink/build/components/App.js:4[6](https://github.com/Patrickrgt/aiko-hydrogen/actions/runs/10838823917/job/30077896296#step:6:6):31)
 -  (node_modules/ink/build/hooks/use-input.js:34:9)
 -commitHookEffectLis (node_modules/react-reconciler/cjs/react-reconciler.devel
  Mount              opment.js:14778:2[6](https://github.com/Patrickrgt/aiko-hydrogen/actions/runs/10838823917/job/30077896296#step:6:7))
 -commitPassiveMountO (node_modules/react-reconciler/cjs/react-reconciler.devel
  Fiber              opment.js:16609:11)
 -commitPassiveMountEffect (node_modules/react-reconciler/cjs/react-reconciler.
  _complete               development.js:16569:9)
 -commitPassiveMountEffe (node_modules/react-reconciler/cjs/react-reconciler.de
  ts_begin              velopment.js:16556:[7](https://github.com/Patrickrgt/aiko-hydrogen/actions/runs/10838823917/job/30077896296#step:6:8))
 -commitPassiveMountE (node_modules/react-reconciler/cjs/react-reconciler.devel
  fects              opment.js:16544:3)
 -flushPassiveEffect (node_modules/react-reconciler/cjs/react-reconciler.develo
  Impl              pment.js:191[8](https://github.com/Patrickrgt/aiko-hydrogen/actions/runs/10838823917/job/30077896296#step:6:9)2:3)
 -flushPassiveEff (node_modules/react-reconciler/cjs/react-reconciler.developme
  cts            nt.js:1[9](https://github.com/Patrickrgt/aiko-hydrogen/actions/runs/10838823917/job/30077896296#step:6:10)127:14)
 -performSyncWorkOn (node_modules/react-reconciler/cjs/react-reconciler.develop
  oot              ment.js:18184:3)
```

![Image](https://github.com/user-attachments/assets/eaf1c327-9013-4927-a745-80d9ba75270f)

**Comment by Patrickrgt** [comment]
Bumping @QuintonC

**Comment by QuintonC** [comment]
@Patrickrgt Have you explored https://github.com/Shopify/hydrogen/issues/1945 to see if the recommended solutions here resolve the error?

This project example is quite behind and hasn't been upgraded in a while. It's a bit outdated when compared with the other projects / templates for Hydrogen. 

For context, the main changes in this example are outlined in the developer documentation guide which walk you through the gating implementation for a Hydrogen project.

Can you reference the issue I shared above and see if that helps at all?
